# Generated by Django 6.0 on 2026-01-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryDiscountEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('id_type', models.CharField(choices=[('dd_form_214', 'DD Form 214 (Certificate of Release or Discharge from Active Duty)'), ('military_retiree_id', 'Military Retiree ID Card'), ('va_veteran_id', 'VA Veteran ID Card (VIC)'), ('state_driver_id', "State-Issued Driver's License/ID with Veteran Designation"), ('active_duty_cac', 'Active Duty Common Access Card (CAC) for current military members')], max_length=50)),
                ('document_file', models.FileField(upload_to='military_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
