# Generated by Django 6.0 on 2026-01-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_discount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='militarydiscountenrollment',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='militarydiscountenrollment',
            name='id_type',
            field=models.CharField(choices=[('DD Form 214', 'DD Form 214'), ('Military Retiree ID Card', 'Military Retiree ID Card'), ('VA Veteran ID Card', 'VA Veteran ID Card'), ('State Issued Veteran ID', 'State Issued Veteran ID'), ('Active Duty CAC', 'Active Duty CAC')], max_length=255),
        ),
    ]
