# Generated by Django 6.0 on 2025-12-26 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('limit', models.IntegerField(blank=True, help_text='Total usage limit', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], default='flat', max_length=20)),
                ('is_use_once_per_customer', models.BooleanField(default=True)),
                ('related_product', models.JSONField(blank=True, help_text='Array of product IDs', null=True)),
                ('related_plan', models.JSONField(blank=True, help_text='Array of plan IDs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
