# Generated by Django 6.0 on 2026-01-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='sim_type',
            field=models.CharField(choices=[('psim', 'pSIM'), ('esim', 'eSIM')], max_length=20),
        ),
    ]
