# Generated by Django 6.0 on 2026-01-15 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_sim_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Plan Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.AlterField(
            model_name='plan',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='seo/og/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='og_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sim_type',
            field=models.CharField(choices=[('psim', 'Physical SIM'), ('esim', 'eSIM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='twitter_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='twitter_image',
            field=models.ImageField(blank=True, upload_to='seo/twitter/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='plans.plancategory'),
        ),
    ]
