# Generated by Django 6.0 on 2026-01-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plancategory_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='plancategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Plan Categories'},
        ),
        migrations.AlterModelOptions(
            name='planfeature',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='plan',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='og_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='twitter_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/twitter/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
