# Generated by Django 6.0 on 2026-01-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_options_alter_plancategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='sim_type',
            field=models.CharField(choices=[('psim', 'pSIM'), ('esim', 'eSIM')], max_length=10),
        ),
    ]
