# Generated by Django 6.0 on 2026-01-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_plan_sim_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='vcPlanID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
