# Generated by Django 6.0 on 2026-01-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarineDiscountEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('ngo_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('id_type', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='marine_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
