# Generated by Django 6.0 on 2026-01-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDiscountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('student_email', models.EmailField(max_length=254)),
                ('document_type', models.CharField(choices=[('Valid Student ID (Front & Back)', 'Valid Student ID (Front & Back)'), ('Enrollment Verification Letter', 'Enrollment Verification Letter'), ('Transcript', 'Transcript')], max_length=255)),
                ('document_file', models.FileField(upload_to='student_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
